import { defineConfig } from "tsdown";

// Per-component subpath exports land here as charts ship (Phase 2):
//   'src/charts/sparkline/index.tsx', 'src/charts/sparkline/client.tsx', ...
// Each becomes its own entry so consumers pay only for what they import.
// CSS is NOT bundled through tsdown — it ships as one static `styles.css`
// (see plan/19-css-delivery.md) so static charts stay zero-JS.
export default defineConfig({
  entry: [
    "src/index.ts",
    "src/annotations.ts",
    "src/charts/sparkline/index.tsx",
    "src/charts/sparkline/client.tsx",
    "src/charts/sparkbar/index.tsx",
    "src/charts/sparkbar/client.tsx",
    "src/charts/delta/index.tsx",
    "src/charts/delta/client.tsx",
    "src/charts/bullet/index.tsx",
    "src/charts/bullet/client.tsx",
    "src/charts/activity-grid/index.tsx",
    "src/charts/activity-grid/client.tsx",
    "src/charts/trend-arrow/index.tsx",
    "src/charts/trend-arrow/client.tsx",
    "src/charts/status-dot/index.tsx",
    "src/charts/status-dot/client.tsx",
    "src/charts/heat-cell/index.tsx",
    "src/charts/heat-cell/client.tsx",
    "src/charts/progress/index.tsx",
    "src/charts/progress/client.tsx",
    "src/charts/rug-strip/index.tsx",
    "src/charts/rug-strip/client.tsx",
    "src/charts/mini-bar/index.tsx",
    "src/charts/mini-bar/client.tsx",
    "src/charts/pictogram-row/index.tsx",
    "src/charts/pictogram-row/client.tsx",
    "src/charts/seismogram/index.tsx",
    "src/charts/seismogram/client.tsx",
    "src/charts/heat-strip/index.tsx",
    "src/charts/heat-strip/client.tsx",
    "src/charts/dot-plot/index.tsx",
    "src/charts/dot-plot/client.tsx",
    "src/charts/dumbbell/index.tsx",
    "src/charts/dumbbell/client.tsx",
    "src/charts/paired-bars/index.tsx",
    "src/charts/paired-bars/client.tsx",
    "src/charts/slope/index.tsx",
    "src/charts/slope/client.tsx",
    "src/charts/micro-scatter/index.tsx",
    "src/charts/micro-scatter/client.tsx",
    "src/charts/segmented-bar/index.tsx",
    "src/charts/segmented-bar/client.tsx",
    "src/charts/histogram-strip/index.tsx",
    "src/charts/histogram-strip/client.tsx",
    "src/charts/micro-box/index.tsx",
    "src/charts/micro-box/client.tsx",
    "src/charts/progress-ring/index.tsx",
    "src/charts/progress-ring/client.tsx",
    "src/charts/micro-donut/index.tsx",
    "src/charts/micro-donut/client.tsx",
    "src/charts/funnel/index.tsx",
    "src/charts/funnel/client.tsx",
    "src/charts/likert-strip/index.tsx",
    "src/charts/likert-strip/client.tsx",
    "src/charts/waterfall/index.tsx",
    "src/charts/waterfall/client.tsx",
    "src/charts/bump-strip/index.tsx",
    "src/charts/bump-strip/client.tsx",
    "src/charts/dual-sparkline/index.tsx",
    "src/charts/dual-sparkline/client.tsx",
    "src/charts/stacked-area/index.tsx",
    "src/charts/stacked-area/client.tsx",
    "src/charts/ohlc/index.tsx",
    "src/charts/ohlc/client.tsx",
    "src/charts/horizon/index.tsx",
    "src/charts/horizon/client.tsx",
    "src/charts/calendar-strip/index.tsx",
    "src/charts/calendar-strip/client.tsx",
    "src/charts/event-timeline/index.tsx",
    "src/charts/event-timeline/client.tsx",
    "src/charts/coverage-strip/index.tsx",
    "src/charts/coverage-strip/client.tsx",
    "src/charts/benchmark-strip/index.tsx",
    "src/charts/benchmark-strip/client.tsx",
    "src/charts/percentile-ladder/index.tsx",
    "src/charts/percentile-ladder/client.tsx",
    "src/charts/graded-band/index.tsx",
    "src/charts/graded-band/client.tsx",
    "src/charts/icon-array/index.tsx",
    "src/charts/icon-array/client.tsx",
    "src/charts/rate-volume/index.tsx",
    "src/charts/rate-volume/client.tsx",
    "src/charts/net-flow/index.tsx",
    "src/charts/net-flow/client.tsx",
    "src/charts/retention-curve/index.tsx",
    "src/charts/retention-curve/client.tsx",
    "src/charts/burn-chart/index.tsx",
    "src/charts/burn-chart/client.tsx",
    "src/charts/error-budget/index.tsx",
    "src/charts/error-budget/client.tsx",
    "src/charts/control-strip/index.tsx",
    "src/charts/control-strip/client.tsx",
    "src/charts/forecast-cone/index.tsx",
    "src/charts/forecast-cone/client.tsx",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  treeshake: true,
  platform: "neutral",
  outDir: "dist",
});
