import { defineConfig } from "tsdown";

// Per-component subpath exports land here as charts ship (Phase 2):
//   'src/charts/sparkline/index.tsx', 'src/charts/sparkline/client.tsx', ...
// Each becomes its own entry so consumers pay only for what they import.
// CSS is NOT bundled through tsdown — it ships as one static `styles.css`
// (see plan/19-css-delivery.md) so static charts stay zero-JS.
export default defineConfig({
  entry: [
    "src/index.ts",
    "src/charts/sparkline/index.tsx",
    "src/charts/sparkline/client.tsx",
    "src/charts/sparkbar/index.tsx",
    "src/charts/sparkbar/client.tsx",
    "src/charts/delta/index.tsx",
    "src/charts/delta/client.tsx",
    "src/charts/bullet/index.tsx",
    "src/charts/bullet/client.tsx",
    "src/charts/activity-grid/index.tsx",
    "src/charts/activity-grid/client.tsx",
    "src/charts/trend-arrow/index.tsx",
    "src/charts/trend-arrow/client.tsx",
    "src/charts/status-dot/index.tsx",
    "src/charts/status-dot/client.tsx",
    "src/charts/heat-cell/index.tsx",
    "src/charts/heat-cell/client.tsx",
    "src/charts/progress/index.tsx",
    "src/charts/progress/client.tsx",
    "src/charts/rug-strip/index.tsx",
    "src/charts/rug-strip/client.tsx",
    "src/charts/mini-bar/index.tsx",
    "src/charts/mini-bar/client.tsx",
    "src/charts/pictogram-row/index.tsx",
    "src/charts/pictogram-row/client.tsx",
    "src/charts/seismogram/index.tsx",
    "src/charts/seismogram/client.tsx",
    "src/charts/heat-strip/index.tsx",
    "src/charts/heat-strip/client.tsx",
    "src/charts/dot-plot/index.tsx",
    "src/charts/dot-plot/client.tsx",
    "src/charts/dumbbell/index.tsx",
    "src/charts/dumbbell/client.tsx",
    "src/charts/paired-bars/index.tsx",
    "src/charts/paired-bars/client.tsx",
    "src/charts/slope/index.tsx",
    "src/charts/slope/client.tsx",
    "src/charts/micro-scatter/index.tsx",
    "src/charts/micro-scatter/client.tsx",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  treeshake: true,
  platform: "neutral",
  outDir: "dist",
});
