import { defineConfig } from "tsdown";

// Per-component subpath exports land here as charts ship (Phase 2):
//   'src/charts/sparkline/index.tsx', 'src/charts/sparkline/client.tsx', ...
// Each becomes its own entry so consumers pay only for what they import.
// CSS is NOT bundled through tsdown — it ships as one static `styles.css`
// (see plan/19-css-delivery.md) so static charts stay zero-JS.
export default defineConfig({
  entry: [
    "src/index.ts",
    "src/annotations.ts",
    "src/theme.ts",
    // Entrance-motion engine: dynamically imported by motion-gate when a
    // consumer passes `animate` — its own chunk so charts that never animate
    // never load it (plan/04 §8.1, plan/06 §5).
    "src/shared/motion-engine.ts",
    "src/charts/sparkline/index.tsx",
    "src/charts/sparkline/client.tsx",
    "src/charts/sparkbar/index.tsx",
    "src/charts/sparkbar/client.tsx",
    "src/charts/delta/index.tsx",
    "src/charts/delta/client.tsx",
    "src/charts/bullet/index.tsx",
    "src/charts/bullet/client.tsx",
    "src/charts/activity-grid/index.tsx",
    "src/charts/activity-grid/client.tsx",
    "src/charts/trend-arrow/index.tsx",
    "src/charts/trend-arrow/client.tsx",
    "src/charts/status-dot/index.tsx",
    "src/charts/status-dot/client.tsx",
    "src/charts/heat-cell/index.tsx",
    "src/charts/heat-cell/client.tsx",
    "src/charts/progress/index.tsx",
    "src/charts/progress/client.tsx",
    "src/charts/rug-strip/index.tsx",
    "src/charts/rug-strip/client.tsx",
    "src/charts/mini-bar/index.tsx",
    "src/charts/mini-bar/client.tsx",
    "src/charts/pictogram-row/index.tsx",
    "src/charts/pictogram-row/client.tsx",
    "src/charts/seismogram/index.tsx",
    "src/charts/seismogram/client.tsx",
    "src/charts/heat-strip/index.tsx",
    "src/charts/heat-strip/client.tsx",
    "src/charts/dot-plot/index.tsx",
    "src/charts/dot-plot/client.tsx",
    "src/charts/dumbbell/index.tsx",
    "src/charts/dumbbell/client.tsx",
    "src/charts/paired-bars/index.tsx",
    "src/charts/paired-bars/client.tsx",
    "src/charts/slope/index.tsx",
    "src/charts/slope/client.tsx",
    "src/charts/micro-scatter/index.tsx",
    "src/charts/micro-scatter/client.tsx",
    "src/charts/segmented-bar/index.tsx",
    "src/charts/segmented-bar/client.tsx",
    "src/charts/histogram-strip/index.tsx",
    "src/charts/histogram-strip/client.tsx",
    "src/charts/micro-box/index.tsx",
    "src/charts/micro-box/client.tsx",
    "src/charts/progress-ring/index.tsx",
    "src/charts/progress-ring/client.tsx",
    "src/charts/micro-donut/index.tsx",
    "src/charts/micro-donut/client.tsx",
    "src/charts/funnel/index.tsx",
    "src/charts/funnel/client.tsx",
    "src/charts/likert-strip/index.tsx",
    "src/charts/likert-strip/client.tsx",
    "src/charts/waterfall/index.tsx",
    "src/charts/waterfall/client.tsx",
    "src/charts/bump-strip/index.tsx",
    "src/charts/bump-strip/client.tsx",
    "src/charts/dual-sparkline/index.tsx",
    "src/charts/dual-sparkline/client.tsx",
    "src/charts/stacked-area/index.tsx",
    "src/charts/stacked-area/client.tsx",
    "src/charts/ohlc/index.tsx",
    "src/charts/ohlc/client.tsx",
    "src/charts/horizon/index.tsx",
    "src/charts/horizon/client.tsx",
    "src/charts/calendar-strip/index.tsx",
    "src/charts/calendar-strip/client.tsx",
    "src/charts/event-timeline/index.tsx",
    "src/charts/event-timeline/client.tsx",
    "src/charts/coverage-strip/index.tsx",
    "src/charts/coverage-strip/client.tsx",
    "src/charts/benchmark-strip/index.tsx",
    "src/charts/benchmark-strip/client.tsx",
    "src/charts/percentile-ladder/index.tsx",
    "src/charts/percentile-ladder/client.tsx",
    "src/charts/graded-band/index.tsx",
    "src/charts/graded-band/client.tsx",
    "src/charts/icon-array/index.tsx",
    "src/charts/icon-array/client.tsx",
    "src/charts/rate-volume/index.tsx",
    "src/charts/rate-volume/client.tsx",
    "src/charts/net-flow/index.tsx",
    "src/charts/net-flow/client.tsx",
    "src/charts/retention-curve/index.tsx",
    "src/charts/retention-curve/client.tsx",
    "src/charts/burn-chart/index.tsx",
    "src/charts/burn-chart/client.tsx",
    "src/charts/error-budget/index.tsx",
    "src/charts/error-budget/client.tsx",
    "src/charts/control-strip/index.tsx",
    "src/charts/control-strip/client.tsx",
    "src/charts/forecast-cone/index.tsx",
    "src/charts/forecast-cone/client.tsx",
    "src/charts/quantile-dots/index.tsx",
    "src/charts/quantile-dots/client.tsx",
    "src/charts/ab-strips/index.tsx",
    "src/charts/ab-strips/client.tsx",
    "src/charts/shift-histogram/index.tsx",
    "src/charts/shift-histogram/client.tsx",
    "src/charts/pareto-strip/index.tsx",
    "src/charts/pareto-strip/client.tsx",
    "src/charts/data-diff/index.tsx",
    "src/charts/data-diff/client.tsx",
    "src/charts/quadrant-dot/index.tsx",
    "src/charts/quadrant-dot/client.tsx",
    "src/charts/cycle-plot/index.tsx",
    "src/charts/cycle-plot/client.tsx",
    "src/charts/change-point/index.tsx",
    "src/charts/change-point/client.tsx",
    "src/charts/ensemble-ghosts/index.tsx",
    "src/charts/ensemble-ghosts/client.tsx",
    "src/charts/tally-marks/index.tsx",
    "src/charts/tally-marks/client.tsx",
    "src/charts/dice-pips/index.tsx",
    "src/charts/dice-pips/client.tsx",
    "src/charts/fill-word/index.tsx",
    "src/charts/fill-word/client.tsx",
    "src/charts/fat-digits/index.tsx",
    "src/charts/fat-digits/client.tsx",
    "src/charts/thermometer/index.tsx",
    "src/charts/thermometer/client.tsx",
    "src/charts/moon-phase/index.tsx",
    "src/charts/moon-phase/client.tsx",
    "src/charts/hourglass/index.tsx",
    "src/charts/hourglass/client.tsx",
    "src/charts/balance-beam/index.tsx",
    "src/charts/balance-beam/client.tsx",
    "src/charts/sprout-row/index.tsx",
    "src/charts/sprout-row/client.tsx",
    "src/charts/garden-grid/index.tsx",
    "src/charts/garden-grid/client.tsx",
    "src/charts/bubble-row/index.tsx",
    "src/charts/bubble-row/client.tsx",
    "src/charts/music-staff/index.tsx",
    "src/charts/music-staff/client.tsx",
    "src/charts/tree-rings/index.tsx",
    "src/charts/tree-rings/client.tsx",
    "src/charts/city-skyline/index.tsx",
    "src/charts/city-skyline/client.tsx",
    "src/charts/honeycomb/index.tsx",
    "src/charts/honeycomb/client.tsx",
    "src/charts/constellation/index.tsx",
    "src/charts/constellation/client.tsx",
    "src/charts/polar-clock/index.tsx",
    "src/charts/polar-clock/client.tsx",
    "src/charts/spiral-year/index.tsx",
    "src/charts/spiral-year/client.tsx",
    "src/charts/breathing-dot/index.tsx",
    "src/charts/breathing-dot/client.tsx",
    "src/charts/heartbeat-blip/index.tsx",
    "src/charts/heartbeat-blip/client.tsx",
    "src/charts/comet-trail/index.tsx",
    "src/charts/comet-trail/client.tsx",
    "src/charts/orbit-status/index.tsx",
    "src/charts/orbit-status/client.tsx",
    "src/charts/time-in-range/index.tsx",
    "src/charts/time-in-range/client.tsx",
    "src/charts/hypnogram/index.tsx",
    "src/charts/hypnogram/client.tsx",
    "src/charts/eta-bar/index.tsx",
    "src/charts/eta-bar/client.tsx",
    "src/charts/waveform/index.tsx",
    "src/charts/waveform/client.tsx",
    "src/charts/event-raster/index.tsx",
    "src/charts/event-raster/client.tsx",
    "src/charts/rubric-strip/index.tsx",
    "src/charts/rubric-strip/client.tsx",
    "src/charts/token-confidence/index.tsx",
    "src/charts/token-confidence/client.tsx",
    "src/charts/wind-barb/index.tsx",
    "src/charts/star-spoke/index.tsx",
    "src/charts/star-spoke/client.tsx",
    "src/charts/minimap-strip/index.tsx",
    "src/charts/minimap-strip/client.tsx",
    "src/charts/dual-window-meter/index.tsx",
    "src/charts/dual-window-meter/client.tsx",
    "src/charts/depth-wedge/index.tsx",
    "src/charts/depth-wedge/client.tsx",
    "src/charts/partition-strip/index.tsx",
    "src/charts/partition-strip/client.tsx",
    "src/charts/calibration-strip/index.tsx",
    "src/charts/calibration-strip/client.tsx",
    "src/charts/confusion-grid/index.tsx",
    "src/charts/confusion-grid/client.tsx",
    "src/charts/folded-day-band/index.tsx",
    "src/charts/folded-day-band/client.tsx",
    "src/charts/volume-profile/index.tsx",
    "src/charts/volume-profile/client.tsx",
    "src/charts/phase-trace/index.tsx",
    "src/charts/phase-trace/client.tsx",
    "src/charts/trace-fold/index.tsx",
    "src/charts/trace-fold/client.tsx",
    "src/charts/tape-gauge/index.tsx",
    "src/charts/tape-gauge/client.tsx",
    "src/charts/station-glyph/index.tsx",
    "src/charts/station-glyph/client.tsx",
    "src/charts/cohort-triangle/index.tsx",
    "src/charts/cohort-triangle/client.tsx",
    "src/charts/streak-spark/index.tsx",
    "src/charts/streak-spark/client.tsx",
    "src/charts/grade-profile/index.tsx",
    "src/charts/grade-profile/client.tsx",
    "src/charts/win-prob-worm/index.tsx",
    "src/charts/win-prob-worm/client.tsx",
    "src/charts/queue-depth/index.tsx",
    "src/charts/queue-depth/client.tsx",
    "src/charts/spread-band/index.tsx",
    "src/charts/spread-band/client.tsx",
    "src/charts/bias-strip/index.tsx",
    "src/charts/bias-strip/client.tsx",
    "src/charts/percentile-trace/index.tsx",
    "src/charts/percentile-trace/client.tsx",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  treeshake: true,
  // Ship a minified runtime: smaller npm tarball, and correct bytes for
  // consumers that import the ESM directly (Deno, CDN, no bundler). Bundling
  // consumers re-minify anyway; the per-subpath size gate already measures a
  // minified+gzipped build via @size-limit/preset-small-lib, so the published
  // per-chart kB figures are unaffected.
  minify: true,
  platform: "neutral",
  outDir: "dist",
});
