#!/usr/bin/env python3
"""Outline the "microcharts" wordmark into a single SVG path.

    python3 scripts/gen-wordmark-path.py      (from apps/docs)

Writes src/lib/wordmark.ts. The name is set in Open Runde 600 at
letter-spacing -0.016em — the exact treatment the nav, the footer and the
social images use — and the glyphs are converted to outlines so a downloaded
file renders identically on a machine that has never installed the face.
Embedding an @font-face instead would look right in a browser and fall back to
Arial the moment someone opens the file in Figma or Illustrator.

Coordinates come out in a 1000-unit em, baseline at y=0, y down (SVG's
direction), so a consumer scales by fontSize/1000 and positions by baseline.
Kerning is read straight out of GPOS PairPos (there is no `kern` table);
scripts/gen-brand-kit.mjs re-measures the advance in Chromium and fails if
this file and the browser disagree by more than a thousandth of an em.

Open Runde is OFL — ship OpenRunde-OFL.txt anywhere these outlines go.
"""

from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.misc.transform import Transform
from fontTools.ttLib import TTFont

TEXT = "microcharts"
LETTER_SPACING = -0.016  # em — matches tracking-[-0.016em] on every surface
EM = 1000  # output units per em
FONT = Path(__file__).resolve().parents[3] / "assets/fonts/OpenRunde-600-latin.woff2"
OUT = Path(__file__).resolve().parents[1] / "src/lib/wordmark.ts"


def pair_kerning(font, glyphs):
    """Kern values (font units) for consecutive pairs, from GPOS PairPos.

    Covers both formats: 1 (explicit pairs) and 2 (class pairs). Only
    XAdvance on the first glyph is read — that is all a latin kern uses.
    """
    if "GPOS" not in font:
        return {}
    lookups = font["GPOS"].table.LookupList.Lookup
    kern = {}

    def record(a, b, value):
        if value and (a, b) not in kern:
            kern[(a, b)] = value

    for lookup in lookups:
        for sub in lookup.SubTable:
            # Extension lookups wrap the real subtable.
            if getattr(sub, "LookupType", None) == 9 or lookup.LookupType == 9:
                sub = sub.ExtSubTable
            if getattr(sub, "LookupType", lookup.LookupType) != 2:
                continue
            fmt = sub.Format
            coverage = sub.Coverage.glyphs
            if fmt == 1:
                for first, pairset in zip(coverage, sub.PairSet):
                    for pv in pairset.PairValueRecord:
                        v1 = pv.Value1
                        record(first, pv.SecondGlyph, getattr(v1, "XAdvance", 0) if v1 else 0)
            elif fmt == 2:
                c1 = sub.ClassDef1.classDefs
                c2 = sub.ClassDef2.classDefs
                for first in coverage:
                    for second in glyphs:
                        rec = sub.Class1Record[c1.get(first, 0)].Class2Record[c2.get(second, 0)]
                        v1 = rec.Value1
                        record(first, second, getattr(v1, "XAdvance", 0) if v1 else 0)
    return kern


def main():
    font = TTFont(FONT)
    upem = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    hmtx = font["hmtx"]

    names = [cmap[ord(ch)] for ch in TEXT]
    kern = pair_kerning(font, set(names))
    tracking = LETTER_SPACING * upem

    scale = EM / upem
    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{round(v, 1):g}")

    x = 0.0
    for i, name in enumerate(names):
        # y flips here: font units run up from the baseline, SVG runs down.
        glyph_set[name].draw(TransformPen(pen, Transform(scale, 0, 0, -scale, x * scale, 0)))
        x += hmtx[name][0]
        if i + 1 < len(names):
            x += kern.get((name, names[i + 1]), 0) + tracking

    # The advance a browser reports adds tracking after the last glyph too.
    advance = (x + tracking) * scale

    bounds = BoundsPen(glyph_set)
    bx = 0.0
    for i, name in enumerate(names):
        glyph_set[name].draw(TransformPen(bounds, Transform(scale, 0, 0, -scale, bx * scale, 0)))
        bx += hmtx[name][0]
        if i + 1 < len(names):
            bx += kern.get((name, names[i + 1]), 0) + tracking
    x0, y0, x1, y1 = (round(v, 1) for v in bounds.bounds)

    ts = f"""/**
 * The "microcharts" wordmark, outlined. GENERATED by
 * scripts/gen-wordmark-path.py — run it, don't hand-edit it.
 *
 * Open Runde 600, letter-spacing {LETTER_SPACING}em, drawn in a {EM}-unit em with the
 * baseline at y=0 and y running down. To set it at a font size S:
 * `transform="translate(x, baselineY) scale(S / {EM})"`.
 *
 * Open Runde is licensed OFL: ship assets/fonts/OpenRunde-OFL.txt with any
 * distribution of these outlines.
 */
export const WORDMARK_PATH =
  "{pen.getCommands()}";

/** Units per em these coordinates are drawn in. */
export const WORDMARK_EM = {EM};

/** Total advance width, tracking included — what a browser would measure. */
export const WORDMARK_ADVANCE = {round(advance, 1)};

/** Tight ink box of the outlines, baseline-relative (y is negative above it). */
export const WORDMARK_INK = {{
  x0: {x0},
  y0: {y0},
  x1: {x1},
  y1: {y1},
}} as const;

/** Font metrics, same {EM}-unit em: cap is unused by the all-lowercase name,
 *  asc is where the 'h' and the dot of the 'i' top out. */
export const WORDMARK_METRICS = {{
  cap: {round(font["OS/2"].sCapHeight * scale, 1)},
  xHeight: {round(font["OS/2"].sxHeight * scale, 1)},
  asc: {round(-y0, 1)},
}} as const;
"""
    OUT.write_text(ts)
    print(f"wrote {OUT.relative_to(Path.cwd())}")
    print(f"  advance {advance:.1f}  ink {x0},{y0} → {x1},{y1}  path {len(pen.getCommands())} chars")
    print(f"  kerned pairs used: {[p for p in zip(names, names[1:]) if kern.get(p)]}")


main()
