/**
 * Emit `src/lib/charts/preview-live.generated.ts` — a per-slug map of LAZY
 * dynamic imports for each chart's interactive `PreviewLive`. The gallery's
 * client stage (`gallery-stage.tsx`) reads this map so its INITIAL client graph
 * carries zero interactive/motion chart code: static previews render on the
 * server, and each live preview streams in as its own chunk after mount.
 *
 * Every entry is a distinct `import("./<slug>")` string literal so Turbopack
 * code-splits one chunk per chart (an expression import would collapse them into
 * a single context module). Only slugs whose module exports a `PreviewLive`
 * appear — the rest simply stay static.
 *
 * A Vitest guard (`preview-live-generated.test.ts`) fails if this map drifts
 * from the live registry, so a new chart can't silently miss its live upgrade.
 * Regenerate with `pnpm gen:preview-live`.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CHART_MODULES } from "../src/lib/charts/registry";

const slugs = Object.entries(CHART_MODULES)
  .filter(([, mod]) => typeof mod.PreviewLive === "function")
  .map(([slug]) => slug);

const lines = slugs
  .map(
    (slug) =>
      `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(`./${slug}`)}).then((m) => ({ default: m.PreviewLive! })),`,
  )
  .join("\n");

const body = `/* GENERATED by scripts/gen-preview-live.ts — do not edit. Run \`pnpm gen:preview-live\`. */
import type { ComponentType } from "react";

/** Lazy per-slug interactive preview loaders. Each entry is a distinct dynamic
 *  import so the gallery's initial client graph carries zero interactive/motion
 *  chart code; live previews stream in per-chart after mount. Only slugs whose
 *  module exports a \`PreviewLive\` appear here. */
export const PREVIEW_LIVE: Record<string, () => Promise<{ default: ComponentType }>> = {
${lines}
};
`;

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "lib", "charts", "preview-live.generated.ts");
writeFileSync(out, body);
// Normalize to oxfmt (unquoted keys, line wrapping) so the committed snapshot
// stays clean under `format:check` no matter how this template is spaced.
execFileSync("oxfmt", [out], { stdio: "inherit" });
console.log(`gen-preview-live: wrote ${slugs.length} lazy preview loaders to ${out}`);
