/* GENERATED by scripts/gen-preview-live.mjs — do not edit. Run `pnpm gen:preview-live`. */
import type { ComponentType } from "react";

/** Lazy per-slug interactive preview loaders. Each entry is a distinct dynamic
 *  import so the gallery's initial client graph carries zero interactive/motion
 *  chart code; live previews stream in per-chart after mount. Only slugs whose
 *  module exports a `PreviewLive` appear here. */
export const PREVIEW_LIVE: Record<string, () => Promise<{ default: ComponentType }>> = {
  "ab-strips": () => import("./ab-strips.live").then((m) => ({ default: m.PreviewLive! })),
  "activity-grid": () => import("./activity-grid.live").then((m) => ({ default: m.PreviewLive! })),
  "balance-beam": () => import("./balance-beam.live").then((m) => ({ default: m.PreviewLive! })),
  "benchmark-strip": () =>
    import("./benchmark-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "bias-strip": () => import("./bias-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "breathing-dot": () => import("./breathing-dot.live").then((m) => ({ default: m.PreviewLive! })),
  "bubble-row": () => import("./bubble-row.live").then((m) => ({ default: m.PreviewLive! })),
  bullet: () => import("./bullet.live").then((m) => ({ default: m.PreviewLive! })),
  "bump-strip": () => import("./bump-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "burn-chart": () => import("./burn-chart.live").then((m) => ({ default: m.PreviewLive! })),
  "calendar-strip": () =>
    import("./calendar-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "calibration-strip": () =>
    import("./calibration-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "change-point": () => import("./change-point.live").then((m) => ({ default: m.PreviewLive! })),
  "city-skyline": () => import("./city-skyline.live").then((m) => ({ default: m.PreviewLive! })),
  "cohort-triangle": () =>
    import("./cohort-triangle.live").then((m) => ({ default: m.PreviewLive! })),
  "comet-trail": () => import("./comet-trail.live").then((m) => ({ default: m.PreviewLive! })),
  "confusion-grid": () =>
    import("./confusion-grid.live").then((m) => ({ default: m.PreviewLive! })),
  constellation: () => import("./constellation.live").then((m) => ({ default: m.PreviewLive! })),
  "control-strip": () => import("./control-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "coverage-strip": () =>
    import("./coverage-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "cycle-plot": () => import("./cycle-plot.live").then((m) => ({ default: m.PreviewLive! })),
  "data-diff": () => import("./data-diff.live").then((m) => ({ default: m.PreviewLive! })),
  delta: () => import("./delta.live").then((m) => ({ default: m.PreviewLive! })),
  "depth-wedge": () => import("./depth-wedge.live").then((m) => ({ default: m.PreviewLive! })),
  "dice-pips": () => import("./dice-pips.live").then((m) => ({ default: m.PreviewLive! })),
  "dot-plot": () => import("./dot-plot.live").then((m) => ({ default: m.PreviewLive! })),
  "dual-sparkline": () =>
    import("./dual-sparkline.live").then((m) => ({ default: m.PreviewLive! })),
  "dual-window-meter": () =>
    import("./dual-window-meter.live").then((m) => ({ default: m.PreviewLive! })),
  dumbbell: () => import("./dumbbell.live").then((m) => ({ default: m.PreviewLive! })),
  "ensemble-ghosts": () =>
    import("./ensemble-ghosts.live").then((m) => ({ default: m.PreviewLive! })),
  "error-budget": () => import("./error-budget.live").then((m) => ({ default: m.PreviewLive! })),
  "eta-bar": () => import("./eta-bar.live").then((m) => ({ default: m.PreviewLive! })),
  "event-raster": () => import("./event-raster.live").then((m) => ({ default: m.PreviewLive! })),
  "event-timeline": () =>
    import("./event-timeline.live").then((m) => ({ default: m.PreviewLive! })),
  "fat-digits": () => import("./fat-digits.live").then((m) => ({ default: m.PreviewLive! })),
  "fill-word": () => import("./fill-word.live").then((m) => ({ default: m.PreviewLive! })),
  "folded-day-band": () =>
    import("./folded-day-band.live").then((m) => ({ default: m.PreviewLive! })),
  "forecast-cone": () => import("./forecast-cone.live").then((m) => ({ default: m.PreviewLive! })),
  funnel: () => import("./funnel.live").then((m) => ({ default: m.PreviewLive! })),
  "garden-grid": () => import("./garden-grid.live").then((m) => ({ default: m.PreviewLive! })),
  "grade-profile": () => import("./grade-profile.live").then((m) => ({ default: m.PreviewLive! })),
  "graded-band": () => import("./graded-band.live").then((m) => ({ default: m.PreviewLive! })),
  "heartbeat-blip": () =>
    import("./heartbeat-blip.live").then((m) => ({ default: m.PreviewLive! })),
  "heat-cell": () => import("./heat-cell.live").then((m) => ({ default: m.PreviewLive! })),
  "heat-strip": () => import("./heat-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "histogram-strip": () =>
    import("./histogram-strip.live").then((m) => ({ default: m.PreviewLive! })),
  honeycomb: () => import("./honeycomb.live").then((m) => ({ default: m.PreviewLive! })),
  horizon: () => import("./horizon.live").then((m) => ({ default: m.PreviewLive! })),
  hourglass: () => import("./hourglass.live").then((m) => ({ default: m.PreviewLive! })),
  hypnogram: () => import("./hypnogram.live").then((m) => ({ default: m.PreviewLive! })),
  "icon-array": () => import("./icon-array.live").then((m) => ({ default: m.PreviewLive! })),
  "likert-strip": () => import("./likert-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "micro-box": () => import("./micro-box.live").then((m) => ({ default: m.PreviewLive! })),
  "micro-donut": () => import("./micro-donut.live").then((m) => ({ default: m.PreviewLive! })),
  "micro-scatter": () => import("./micro-scatter.live").then((m) => ({ default: m.PreviewLive! })),
  "mini-bar": () => import("./mini-bar.live").then((m) => ({ default: m.PreviewLive! })),
  "minimap-strip": () => import("./minimap-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "moon-phase": () => import("./moon-phase.live").then((m) => ({ default: m.PreviewLive! })),
  "music-staff": () => import("./music-staff.live").then((m) => ({ default: m.PreviewLive! })),
  "net-flow": () => import("./net-flow.live").then((m) => ({ default: m.PreviewLive! })),
  ohlc: () => import("./ohlc.live").then((m) => ({ default: m.PreviewLive! })),
  "orbit-status": () => import("./orbit-status.live").then((m) => ({ default: m.PreviewLive! })),
  "paired-bars": () => import("./paired-bars.live").then((m) => ({ default: m.PreviewLive! })),
  "pareto-strip": () => import("./pareto-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "partition-strip": () =>
    import("./partition-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "percentile-ladder": () =>
    import("./percentile-ladder.live").then((m) => ({ default: m.PreviewLive! })),
  "percentile-trace": () =>
    import("./percentile-trace.live").then((m) => ({ default: m.PreviewLive! })),
  "phase-trace": () => import("./phase-trace.live").then((m) => ({ default: m.PreviewLive! })),
  "pictogram-row": () => import("./pictogram-row.live").then((m) => ({ default: m.PreviewLive! })),
  "polar-clock": () => import("./polar-clock.live").then((m) => ({ default: m.PreviewLive! })),
  progress: () => import("./progress.live").then((m) => ({ default: m.PreviewLive! })),
  "progress-ring": () => import("./progress-ring.live").then((m) => ({ default: m.PreviewLive! })),
  "quadrant-dot": () => import("./quadrant-dot.live").then((m) => ({ default: m.PreviewLive! })),
  "quantile-dots": () => import("./quantile-dots.live").then((m) => ({ default: m.PreviewLive! })),
  "queue-depth": () => import("./queue-depth.live").then((m) => ({ default: m.PreviewLive! })),
  "rate-volume": () => import("./rate-volume.live").then((m) => ({ default: m.PreviewLive! })),
  "retention-curve": () =>
    import("./retention-curve.live").then((m) => ({ default: m.PreviewLive! })),
  "rubric-strip": () => import("./rubric-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "rug-strip": () => import("./rug-strip.live").then((m) => ({ default: m.PreviewLive! })),
  "segmented-bar": () => import("./segmented-bar.live").then((m) => ({ default: m.PreviewLive! })),
  seismogram: () => import("./seismogram.live").then((m) => ({ default: m.PreviewLive! })),
  "shift-histogram": () =>
    import("./shift-histogram.live").then((m) => ({ default: m.PreviewLive! })),
  slope: () => import("./slope.live").then((m) => ({ default: m.PreviewLive! })),
  sparkbar: () => import("./sparkbar.live").then((m) => ({ default: m.PreviewLive! })),
  sparkline: () => import("./sparkline.live").then((m) => ({ default: m.PreviewLive! })),
  "spiral-year": () => import("./spiral-year.live").then((m) => ({ default: m.PreviewLive! })),
  "spread-band": () => import("./spread-band.live").then((m) => ({ default: m.PreviewLive! })),
  "sprout-row": () => import("./sprout-row.live").then((m) => ({ default: m.PreviewLive! })),
  "stacked-area": () => import("./stacked-area.live").then((m) => ({ default: m.PreviewLive! })),
  "star-spoke": () => import("./star-spoke.live").then((m) => ({ default: m.PreviewLive! })),
  "station-glyph": () => import("./station-glyph.live").then((m) => ({ default: m.PreviewLive! })),
  "status-dot": () => import("./status-dot.live").then((m) => ({ default: m.PreviewLive! })),
  "streak-spark": () => import("./streak-spark.live").then((m) => ({ default: m.PreviewLive! })),
  "tally-marks": () => import("./tally-marks.live").then((m) => ({ default: m.PreviewLive! })),
  "tape-gauge": () => import("./tape-gauge.live").then((m) => ({ default: m.PreviewLive! })),
  thermometer: () => import("./thermometer.live").then((m) => ({ default: m.PreviewLive! })),
  "time-in-range": () => import("./time-in-range.live").then((m) => ({ default: m.PreviewLive! })),
  "token-confidence": () =>
    import("./token-confidence.live").then((m) => ({ default: m.PreviewLive! })),
  "trace-fold": () => import("./trace-fold.live").then((m) => ({ default: m.PreviewLive! })),
  "tree-rings": () => import("./tree-rings.live").then((m) => ({ default: m.PreviewLive! })),
  "trend-arrow": () => import("./trend-arrow.live").then((m) => ({ default: m.PreviewLive! })),
  "volume-profile": () =>
    import("./volume-profile.live").then((m) => ({ default: m.PreviewLive! })),
  waterfall: () => import("./waterfall.live").then((m) => ({ default: m.PreviewLive! })),
  waveform: () => import("./waveform.live").then((m) => ({ default: m.PreviewLive! })),
  "win-prob-worm": () => import("./win-prob-worm.live").then((m) => ({ default: m.PreviewLive! })),
  "wind-barb": () => import("./wind-barb.live").then((m) => ({ default: m.PreviewLive! })),
};
