/**
 * Generate the committed snapshots the package ships:
 *   - src/catalog.generated.json  — chart metadata (no version stamp: the
 *                                    library version is injected at build time,
 *                                    see src/version.ts)
 *   - src/assets.generated.ts      — the built stylesheet (embedded for self-
 *                                    contained render() SVGs) + the agent-setup
 *                                    prompt, as string literals a bundler inlines
 *
 * Source of truth lives in the monorepo (the docs registry + the built library),
 * never in the published package. Run under `tsx` (`pnpm gen`); re-run whenever
 * the registry or stylesheet changes. `catalog-sync.test.ts` fails CI if the
 * committed snapshots drift from these sources.
 *
 * The library must be BUILT first (`pnpm build` at the repo root) so
 * `dist/styles.css` exists — `pnpm gen` reads it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";
import type { ChartProp } from "../src/types";
import { projectCatalog, type ProjectionReport, type RegistryEntry } from "./project";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const docs = resolve(root, "apps/docs");
const out = resolve(here, "../src");

function read(path: string): string {
  return readFileSync(path, "utf8");
}

// Chart metadata — the registry's pure-JSON snapshot (already guard-tested).
const registry = JSON.parse(
  read(resolve(docs, "src/lib/charts/entries.generated.json")),
) as RegistryEntry[];

// Shared grammar/layout/i18n props (TS module → imported under tsx).
const { SHARED_PROPS } = (await import(
  pathToFileURL(resolve(docs, "src/lib/charts/shared-props.ts")).href
)) as { SHARED_PROPS: ChartProp[] };

// The agent-setup prompt — extracted from quickstart.mdx (single source of truth).
const { extractAgentSetupPrompt } = (await import(
  pathToFileURL(resolve(docs, "src/lib/agent-setup.ts")).href
)) as { extractAgentSetupPrompt: (mdx: string) => string };
const agentSetup = extractAgentSetupPrompt(read(resolve(docs, "content/docs/quickstart.mdx")));

// The built stylesheet — embedded whole so a rendered SVG is self-contained.
const styles = read(resolve(root, "dist/styles.css"));

const report: ProjectionReport = { skippedProps: [], noSample: [] };
const catalog = projectCatalog(registry, SHARED_PROPS, report);

const assets = `// GENERATED by scripts/gen.ts — do not edit. Run \`pnpm gen\`.
/* eslint-disable */
export const STYLES: string = ${JSON.stringify(styles)};

export const AGENT_SETUP: string = ${JSON.stringify(agentSetup.trim() + "\n")};
`;

writeFileSync(resolve(out, "catalog.generated.json"), JSON.stringify(catalog, null, 2) + "\n");
writeFileSync(resolve(out, "assets.generated.ts"), assets);

const withSample = catalog.charts.filter((c) => c.sample).length;
console.log(
  `gen: ${catalog.charts.length} charts (${withSample} with a render sample), ${SHARED_PROPS.length} shared props, styles ${styles.length}B`,
);
if (report.noSample.length > 0)
  console.log(`gen: no sample derived for ${report.noSample.join("; ")}`);
if (report.skippedProps.length > 0)
  console.log(`gen: non-JSON example props skipped — ${report.skippedProps.join(" | ")}`);
