import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque, Hanken_Grotesk, JetBrains_Mono } from "next/font/google";
import { Provider } from "@/components/provider";
import { SITE } from "@/lib/site";
import {
  jsonLdScript,
  organizationJsonLd,
  softwareApplicationJsonLd,
  softwareSourceCodeJsonLd,
  websiteJsonLd,
} from "@/lib/jsonld";
import { SEO_KEYWORDS } from "@/lib/seo";
import "./global.css";

const sans = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans-src",
  display: "swap",
});

const display = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-display-src",
  display: "swap",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono-src",
  display: "swap",
});

// Apply saved accent + chart preset before first paint.
const ACCENT_SCRIPT = `try{var d=document.documentElement,a=localStorage.getItem("mc-accent");if(a&&a!=="ember")d.dataset.accent=a;var p=localStorage.getItem("mc-preset");if(p&&p!=="modern")d.dataset.mcPreset=p}catch(e){}`;

// Predict the hero's live-mode layout before first paint, so the panel is born
// its final size instead of growing into it.
//
// `LanguageModel.availability()` is async and settles well after paint — that
// lateness is the whole problem. But the *presence* of the API is synchronous,
// and whether the model is actually on disk is stable across visits, so one
// remembered bit plus one sync check predicts the layout precisely: the API has
// to exist here AND Nano has to have been installed last time. Both true ->
// reserve. A visitor without Chrome's AI never matches and pays one `typeof`.
//
// The flag is written and cleared by use-live-model.ts against the real
// availability answer, so an uninstalled model self-heals on the next load.
const LIVE_SCRIPT = `try{if(typeof LanguageModel!=="undefined"&&localStorage.getItem("mc-live")==="1")document.documentElement.dataset.mcLive="1"}catch(e){}`;

// The leading glyph is the hero's own sparkline data ([3,5,4,8,6,9,7,11])
// rendered in unicode blocks — a chart small enough to sit in a console.log,
// which is exactly the tagline. Delight that doesn't lie: it's the real series.
const CONSOLE_SCRIPT = `try{console.log("%c▁▃▂▅▄▆▅█%c  ${SITE.name}%c\\n${SITE.tagline}\\nThat glyph is the hero's sparkline in text. Small enough for a sentence, a table cell, or a console.log.\\nZero dependencies, ~2–7 kB interactive · ~1–4 kB static per chart, accessible by default.\\n\\nDocs    ${SITE.url}/docs\\nSource  ${SITE.repo}","color:#c2410c;font-size:15px;letter-spacing:1.5px","color:#c2410c;font-weight:700;font-size:13px","color:#8a8986;font-size:11px;line-height:1.7")}catch(e){}`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  // Keyword tail on the SERP title only — OG/twitter keep the clean brand line.
  title: {
    default: `${SITE.name} — ${SITE.tagline} Tiny sparklines & micro charts.`,
    template: `%s · ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  authors: [{ name: SITE.author, url: SITE.authorUrl }],
  creator: SITE.author,
  publisher: SITE.author,
  keywords: [...SEO_KEYWORDS],
  category: "technology",
  alternates: {
    canonical: "/",
    types: {
      "application/atom+xml": [{ url: "/rss.xml", title: `${SITE.name} releases` }],
      "text/plain": [{ url: "/llms.txt", title: `${SITE.name} for LLMs` }],
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  // Crisp env-aware SVG favicon (app/brand/icon.svg). The apple-touch icon must
  // be listed explicitly — an `icons` object suppresses the app/apple-icon.tsx
  // file convention's automatic <link> tag. favicon.ico (app/favicon.ico,
  // regenerated by scripts/gen-favicon.py) + the 192px PNG exist for Google
  // SERP favicon rules (48px-multiple raster) and legacy /favicon.ico probes.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48 32x32 16x16", type: "image/x-icon" },
      { url: "/icon-192", sizes: "192x192", type: "image/png" },
      { url: "/brand/icon.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    siteName: SITE.name,
    title: `${SITE.name} — ${SITE.tagline}`,
    description: SITE.description,
    url: SITE.url,
    locale: "en_US",
    images: [
      {
        url: "/og/default.png",
        width: 1200,
        height: 630,
        alt: SITE.ogImageAlt,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: SITE.authorXHandle,
    creator: SITE.authorXHandle,
    title: `${SITE.name} — ${SITE.tagline}`,
    description: SITE.description,
    images: [{ url: "/og/default.png", alt: SITE.ogImageAlt }],
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#e9edf4" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0b0f" },
  ],
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // "cold" = this document painted from server HTML, so entrance
      // animations must not gate that paint. Flipped to "warm" by <Provider>
      // once the first page is on screen; from then on every transition is an
      // SPA one, where the animation costs nothing the reader is waiting for.
      data-boot="cold"
      className={`${sans.variable} ${display.variable} ${mono.variable}`}
      suppressHydrationWarning
    >
      <body className="flex flex-col min-h-screen font-sans antialiased">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:rounded-md focus:bg-fd-background focus:px-3 focus:py-2 focus:text-sm focus:font-medium focus:text-fd-foreground focus:shadow-md focus:ring-2 focus:ring-fd-primary"
        >
          Skip to content
        </a>
        <script dangerouslySetInnerHTML={{ __html: ACCENT_SCRIPT }} />
        <script dangerouslySetInnerHTML={{ __html: LIVE_SCRIPT }} />
        <script dangerouslySetInnerHTML={{ __html: CONSOLE_SCRIPT }} />
        <script type="application/ld+json">{jsonLdScript(organizationJsonLd())}</script>
        <script type="application/ld+json">{jsonLdScript(websiteJsonLd())}</script>
        <script type="application/ld+json">{jsonLdScript(softwareSourceCodeJsonLd())}</script>
        <script type="application/ld+json">{jsonLdScript(softwareApplicationJsonLd())}</script>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
