import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { describeSeries, EN } from "@microcharts/react";
import { calendarStripSummary } from "@microcharts/react/calendar-strip";

// accessibility.mdx hand-types the exact `describeSeries` output for known
// inputs (the hero sentence + the degenerate-data table). Those literals are
// the library's actual generated strings — but nothing regenerated them, so a
// change to the generator's wording would rot the page silently. Here we run
// the real generator and assert the page still contains its output, so any
// wording change forces the docs to be updated in the same PR.
const a11y = readFileSync(resolve(process.cwd(), "content/docs/accessibility.mdx"), "utf8");

// Each input is shown verbatim in accessibility.mdx next to its summary.
const INPUTS: readonly (number | null)[][] = [
  [], // "No data."
  [7], // "Single value 7."
  [5, 5, 5, 5], // "Flat at 5."
  [9, 7, 8, 4, 5, 2], // "Trending down 78%. Range 2 to 9. Last value 2."
  [3, 5, 4, 8, 6, 9], // hero: "Trending up 200%. Range 3 to 9. Last value 9."
];

describe("accessibility.mdx quotes real describeSeries output", () => {
  for (const data of INPUTS) {
    const out = describeSeries(data);
    it(`contains the generated summary for ${JSON.stringify(data)} — "${out}"`, () => {
      expect(a11y, `expected accessibility.mdx to quote "${out}"`).toContain(out);
    });
  }
});

// mcp.mdx documents how `render_microchart` behaves on degenerate input by
// quoting the sentence each case produces. Same rule as above: the tool reads
// the summary back out of the rendered markup, so these must be the generator's
// real output, not a description of it.
const mcp = readFileSync(resolve(process.cwd(), "content/docs/mcp.mdx"), "utf8");

const MCP_INPUTS: readonly (number | null)[][] = [
  [], // "No data."
  [7], // "Single value 7."
  [5, 5, 5, 5], // "Flat at 5."
  [3, null, 5, null, 9], // nulls are gaps, not zeros
  [NaN, 3, Infinity], // non-finite dropped
  [-4, -2, -8], // negatives
  [132, 148, 141, 165, 159, 182], // the render_microchart example call
];

describe("mcp.mdx quotes real describeSeries output", () => {
  for (const data of MCP_INPUTS) {
    const out = describeSeries(data);
    it(`contains the generated summary for ${JSON.stringify(data)} — "${out}"`, () => {
      expect(mcp, `expected mcp.mdx to quote "${out}"`).toContain(out);
    });
  }
});

// Same rule, different generator: formatting.mdx quotes a CalendarStrip summary
// to explain why `format` doesn't restyle a day count. That literal was once
// hand-invented ("Active 11 of 24 days over 4 weeks." — 4 weeks is 28 days), so
// it is now generated by the shipped function the chart itself calls.
const formatting = readFileSync(resolve(process.cwd(), "content/docs/formatting.mdx"), "utf8");

describe("formatting.mdx quotes a real calendarStripSummary output", () => {
  const out = calendarStripSummary(3, 28, 4, EN);
  it(`contains "${out}"`, () => {
    expect(formatting, `expected formatting.mdx to quote "${out}"`).toContain(out);
  });
});
